- README.md
I've added a small section that attempts to describe the interaction with `Map`, `Set`, and `WeakMap`, as well as an example of each.
> Added a section to clarify usage inside standard collections Map/Set/WeakMap

- README.md
The actual value hasn't been decided on, but I added a section that describes that the `typeof` const objects/arrays is not `object`, but some other value (placeholder for now).
This will conflict with my other PRs, I will take care of rebasing etc when the time comes.
> Added section to specify that typeof will return a new value

- README.md
I've added a note about enumeration order in order to clarify the behavior for const objects and const arrays.
> Clarified enumeration order of properties

- README.md
Mostly mechanical change here. I slightly tweaked the section on "const vs `@const`", now that `@const` isn't a thing.
> Converted from @const to #{} and #[]

- README.md
Just like their mutable counterparts, `const objects` are not iterable, while `const arrays` are.
> Clarify that const arrays are iterable, while const objects are not

- README.md
I added a new section in the FAQ about `# vs keyword` pros/cons.
I also cleaned up a bit of the style. The doc is getting a bit long, so bumping up the section headers one size, and the subheaders one size, helps with readability IMO.
> Added new section in the FAQ about # vs keyword, cleaned up styles

- README.md
[WIP]! I likely missed something / broke something, so this needs another pass.
This is the first pass of renaming "const values types" -> "Record" and "Tuple". I attempted to replace all usage/reference to the new types as objects/constant value types with their proper names. This required slightly changing the wording in some places in order to be less ambiguous. 
So far, I have left the `Syntax` section unchanged, and they still refer `const`. What do we want to do here?
> [WIP] Initial pass of converting to Record/Tuple naming

- README.md
- Add Object.from(record)
- Add behavior of JSON.stringify(tuple) and
JSON.stringify(record)
- Clarify what values are allowed as
keys/values of records and as entries in tuples
fix #39
> Add JSON roundtripping goal and consequences

- README.md
- Clarify what we what we currently know about how the [four equality algorithms of JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness) interact with `Record` and `Tuple`.
- Note that we have not yet decided on how insertion order interacts with equality.
- Update wording to make it clear that there are no boxed Records or Tuples.
close https://github.com/rricard/proposal-const-value-types/issues/20
> clarify equality

- README.md
> Remove JSON roundtripping part

- README.md
This is still contestable at that point but we are edging to removing the `with` part of the proposal to make it easier to reason with for the time being. As a followup, we should have an orthogonal proposal that would introduce that feature everywhere in the language (not only for const value types)
> Remove with from the proposal

- README.md
> order with the default comparator

- README.md
Update our explainer to reflect that record keys are not ordered
We determined that having a notion of equality for records
that is dependent on insertion order would have poor
ergonomics and would not buy us any performance gain.
This PR does *not* resolve the question of what the sort function will be for the return value of `Record.keys`. @rickbutton is working on that.
> "record keys are not ordered

- NS-Proto-Appendix.md
I've attempted to fill out the prototype/namespace appendix with the `Tuple` prototype.
I wasn't entirely sure how much detail to provide for each method, so I went with a high level overview of behavior, and argument descriptions.
As discussed, this is effectively the `Array.prototype` with changes to shift/unshift/pop/push to deal with immutability, and new methods with/first/last.
> added Tuple.prototype methods to appendix

- README.md
in reference to #65 
cc @bakkot
> updated equality examples to reflect === semantics

- README.md
This change fixes #40, fixes #74, fixes #88.
If anything is too controversial, I can isolate a commit and discuss it further in an another PR.
> Improvements covering a few ongoing issues

- README.md
> Added note that clarifies that Record&Tuple prototypes are adopted from the current realm

- README.md
Fixes #90
Adds another computed access example that shows:
- A boolean computed key which is coerced to a string
- An addition expression key which is coerced to a string
**Edited**
Added descriptive language and the following scenarios:
- Computed keys example
- Keys are coerced to strings
- Shorthand notation
I revised the spread operator snippet to show a simple scenario, a scenario where a key is specified twice with the second value taking precedence and called out order not affecting equality.
> Add another computed access example

- README.md
> added several early syntax errors

- README.md
A `WeakSet` also doesn't accept primitive values, only objects as its
elements. As such it should be mentioned in the readme alongside
`WeakMap`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet
> Mention WeakSet along with WeakMap

- .gitignore
- .vscode/settings.json
- package.json
- spec.html
- spec/data-types-and-values.html
- spec/expression.html
- spec/immutable-data-structures.html
- spec/lexical-grammar.html
- spec/overview.html
- spec/syntax.html
This PR structures the proposal's spec text around ECMA262's structure.
Additionally this creates a tentative grammar
Draft is up here: http://tc39.es/proposal-record-tuple/
> Spec text structure & Attempt at grammar

- NS-Proto-Appendix.md
This was included before, and turns out to be needed in the context of #71
> Add back Record.isRecord

- spec/immutable-data-structures.html
- spec/overview.html
NOTE: This is an early and incomplete draft. Comments welcome.
> Initial Record/Tuple standard library spec

- spec.html
- spec/data-types-and-values.html
- spec/fundamental-objects.html
in response to #136 , I will draft another PR that experiments with the "useful" output version, but at the very least the "less useful" version should return `[object Record]` for `ToString`, and `Object.prototype.toString`.
> added to Object.prototype.toString and reflected in ToString

- spec/immutable-data-structures.html
Without first ensuring that the index is a number, `>=` isn't defined.
> Add missing ToIndex conversion in Tuple.prototype.with

- spec/structured-data.html
This pull request adds the definition of the `JSON.parseImmutable` function.
The implementation proposed here passes `undefined` as the `this` object of the `reviver` function, for the reason explained at https://github.com/tc39/proposal-record-tuple/issues/120#issuecomment-658997804, but we can still change it in the future.
> Write spec for JSON.parseImmutable

- NS-Proto-Appendix.md
- README.md
These methods are not in the spec, and they can be replaced with `Object.*` functions.
> Remove mentions of static Record methods

- spec.html
- spec/structured-data.html
This pull request adds support for records and tuples to `JSON.stringify`. They are serialized exactly as if they were objects or arrays, reusing the existing spec as much as possible.
The `replacer` and `space` parameters still work exactly like they work with objects.
Most of the text in this PR is copied from the ecma262 spec. I marked the additions with `<ins>`.
> Update JSON.stringify to support Records and Tuples

- spec/immutable-data-structures.html
These two methods aren't mentioned anywhere and they aren't included in the polyfill, but I _think_ that it's just because this proposal was created before that those two methods have been merged to the main spec.
> Add Tuple.prototype.{flat,flatMap}

- README.md
- cookbook/en.md
- spec/immutable-data-structures.html
`.slice` doesn't mutate the array, so we shouldn't rename it.
> Rename .sliced to .slice, since .slice doesn't mutate the array

- spec/immutable-data-structures.html
`_kValue_` was already a Tuple element, so we don't need to check its type.
> Remove unnecessary check from .slice

- spec/immutable-data-structures.html
Fixes https://github.com/tc39/proposal-record-tuple/issues/171
If the spec text looks good I'll re-use it for all the other methods carried over from `Array.prototype`.
> Consistent brand checks for tuple methods

- spec/immutable-data-structures.html
Since those are functions, their internal `[[Prototype]]` slot should be `Function.prototype`. `%Tuple.prototype%` and `null` are already (correctly) used as the values of their `.prototype` property.
> Fix [[Prototype]] of Record and Tuple constructors

- spec/immutable-data-structures.html
The current spec only creates a clone of the list instead of reversing it.
> Fix Tuple.prototype.reversed()

- spec/immutable-data-structures.html
It's passed to _mapperFunction_
> Add missing variable in FlattenIntoTuple

- spec/immutable-data-structures.html
I'm opening this PR to seek feedback.
The current spec for the `Tuple` constructor matches the `Array` behavior:
1. If it receives zero arguments, it creates an empty tuple
2. If it receives a single numeric argument `n`, it creates a tuple containing `undefined` `n` types (for arrays, it creates `n` holes)
3. If it receives a single non-numeric argument `x`, it creates the tuple `#[ x ]`
4. If it receives two or more arguments `...xs`, it creates the tuple `#[ ...x ]`
`new Array(n)` is often used to pre-allocate the array before initialising its elements instead of `.push`ing multiple times, for performance reasons. On the other side, the difference between `new Array(4)` and `new Array("4")`/`new Array(4, 5)` can create confusion.
With tuples, we can't optimise the initialisation like …
> Don't overload the Tuple constructor

- spec/abstract-operations.html
- spec/data-types-and-values.html
- spec/expression.html
- spec/fundamental-objects.html
- spec/immutable-data-structures.html
- spec/ordinary-and-exotic-object-behaviours.html
- spec/overview.html
This PR shows how boxes can fit the current proposal, making it possible to store mutable state inside of records and tuples.
In order to store an object inside a record/tuple, it must be wrapped via `Box(obj)`, and it the wrapped value can be obtained using `box.unbox()`.
Open questions:
1. Should `===` defer to the boxed values, or behave like it does for records? i.e. `Box(NaN) === Box(NaN)`?
- 👍 note by @rricard: looks like from the thread: yes it should defer to the values and is spec'ed as-so
1. Should `ToNumber(box)` and `ToBoolean(box)` return the result of calling that operation on the boxed value?
- 👍 note by @rricard: looks like from the thread: no and is spec'ed as-so
1. Should boxes be only allowed to contain objects? Any value? Any value except for boxes?
- 👍 note by …
> Add support for Boxes

- spec/abstract-operations.html
- spec/expression.html
- spec/immutable-data-structures.html
- spec/structured-data.html
Record fields were sorted only when created with the `#{ ... }` syntax, and not when created by a built-in function.
This PR consistently sorts them, so that the algorithms relying on a well-defined order (for example, `RecordEqual` don't break.
> Consistently sort record fields

- spec/expression.html
This doesn't need the `CreateRecord` abstract operation defined by https://github.com/tc39/proposal-record-tuple/pull/234, we don't need to sort an empty list.
> Fix "Runtime Semantics: Evaluation" of record literals

- cookbook/en.md
It was probably a leftover from copy-pasting a `Map` example.
> Change variable name in cookbook

- spec/structured-data.html
This is a draft implementation that fixes https://github.com/tc39/proposal-record-tuple/issues/232.
I tried to respect the following constraints which are already respected by the current `JSON.stringify` implementation:
1. `.toJSON` is called at most once
2. `.toJSON` can only be called before calling the replacer
And I added the following rules:
1. boxes are never unboxed before calling the replacer (so that you can have a custom serialization for them - https://github.com/tc39/proposal-record-tuple/issues/232#issuecomment-878992408)
2. objects inside boxes can still be `.toJSON`ed
3. nested boxes are recursively unboxed
4. boxes are always unboxes before trying to serialize them
I decided not to implement this property, which is an alternative to (1) (they cannot be both implemented): …
> Unwrap boxes in `JSON.stringify`

- package-lock.json
- package.json
- spec/abstract-operations.html
- spec/data-types-and-values.html
- spec/expression.html
- spec/immutable-data-structures.html
- spec/ordinary-and-exotic-object-behaviours.html
- spec/overview.html
- spec/structured-data.html
I was trying to copy-past some algorithms from the spec to the proposal, and I was getting build errors.
I realized that it was because of https://github.com/tc39/ecma262/pull/545. This PR isn't strictly necessary now (it could be done when opening the PR to the main spec), but it'll make things easier if/when we need to change the proposal spec.
> Update ecmarkup to v9

- spec/expression.html
This aligns it with spread in object literals.
> Only get enumerable properties when spreading in records

- spec/immutable-data-structures.html
- spec/ordinary-and-exotic-object-behaviours.html
We where using them interchangeably, but we must be careful to:
- only compare numbers of the same type
- not expose reals to JS
> Fix reals/floats usage

- NS-Proto-Appendix.md
- spec/immutable-data-structures.html
They have been renamed, and `.with` changed how it validates its parameters.
> Rename methods from the change-array-by-copy proposal

- .github/workflows/publish.yml
The action isn't currently running
> Rename `master` -> `main` in publish workflow

- spec/ordinary-and-exotic-object-behaviours.html
AFAICT, RecordHasProperty cannot throw and other places where it gets invoked already use `!`.
> Record exotic object [[Delete]] was using `?` for a `!` case

- spec/abstract-operations.html
- spec/overview.html
The last step in IsConcatSpreadable is presumably still meant to be `Return ? IsArray(_O_).`
> Is concat spreadable step 5 error/typo

- spec/immutable-data-structures.html
There was only one usage of [[TupleValue]], which isn’t defined & appears to be intended to be a ref to [[TupleData]] instead.
> TupleValue slot → TupleData slot (typo AFAICT)

- README.md
> assert(Object.keys(#{ a: 1, b: 2 }) === #["a", "b"]);
should be
> assert(Object.keys(#{ a: 1, b: 2 }) !== #["a", "b"]);
> Fix Object.keys(#{ a: 1, b: 2 }) === #["a", "b"]

- scripts/build-static-page.mjs
Marked was recently updated to v4 in the dependencies, but the code wasn't updated
Makes the tests pass: https://github.com/tc39/proposal-record-tuple/runs/4914554367?check_suite_focus=true 
Breaking change noted in https://github.com/markedjs/marked/releases/tag/v4.0.0
> Update marked import

- README.md
According to the [Record & Tuple spec text](https://tc39.es/proposal-record-tuple/#sec-record.fromentries), the parameters of `Record.fromEntries` should be iterable and each item should just match the key, value definition of Record.
Perhaps a more general case to consider here is `Object.entries` return value of a regular object.
> Fix Record.fromEntries example

- spec/immutable-data-structures.html
This coerces keys to strings like Object.fromEntries would do while rejecting symbols as they cannot be record keys
> spec: make sure we get string keys in Record.fromEntries

- spec/immutable-data-structures.html
- spec/ordinary-and-exotic-object-behaviours.html
Closes #282 
Looks like my editor trimmed a bunch of trailing whitespace too. Recommend viewing diff with[ ignoreWhitespace enabled](https://github.com/tc39/proposal-record-tuple/pull/310/files?diff=unified&w=1)
> 'length' is an own property on Tuple

- spec.html
- spec/immutable-data-structures.html
- spec/purely-editorial.html
Fixes https://github.com/tc39/proposal-record-tuple/issues/266
The `Tuple.from` spec was completely wrong. It was calling `AddEntriesFromIterable`, which expects the iterator to return `key,value` pairs, and then it was ignoring the keys. With the old spec, `Tuple.from([ #[3, 4], #["ab", "cd"] ])` would return `#[4, "cd"]`; with the new one it returns `#[ #[3, 4], #["ab", "cd"] ]` which is consistent with `Array.from`.
> Fix `Tuple.from`

- spec/expression.html
`#{ __proto__ }` and `#{ ["__proto__"]: something }`  are still allowed, because when used in objects they don't set the object's prototype.
Fixes https://github.com/tc39/proposal-record-tuple/issues/313.
> Disallow `#{ __proto__: something }`

- spec/abstract-operations.html
- spec/fundamental-objects.html
Closes #289 
The current spec does not have a _useful_ ToString result for record: `"[object Record]"`. #136 
While the returned string is not useful it likely makes sense to also throw an error to catch accidental implicit conversion of a record to string:
```js
const rec = #{ prop: 42 };
// Explicit:
Object.prototype.toString.call(rec); // `[object Record]`
String(rec); // `[object Record]`
JSON.stringify(rec); // `{"prop":42}`
rec.toString(); // Throws "toString is not a function"
// Implicit:
`${rec)`; // Throws
"" + rec; // Throws
```
If the decision was made to change RecordToString to return a useful string then this PR would almost certainly be reverted.
> Implicit conversion of record to string throws TypeError

- spec/abstract-operations.html
Closes #320 
An alternative approach would be to add `Symbol.toPrimitive` on all Record wrappers, though this would introduce a new hidden intrinsic.
> no longer throw for toPrimitive of a record wrapper

- package-lock.json
- package.json
- spec/abstract-operations.html
First commit fixes the syntax for Records in header types to match 262 (and to make ecmarkup happy).
Second commit pins the biblio, as is [recommended in its readme](https://www.npmjs.com/package/@tc39/ecma262-biblio).
> fix ecmarkup syntax & pin biblio

- NS-Proto-Appendix.md
- spec/immutable-data-structures.html
Fixes #329 #333 #335
Removes `Record.isRecord` and `Tuple.isTuple`
Adds `Record.recordValue`
```js
Record.recordValue(#{}); // #{}
Record.recordValue(Object(#{})); // #{}
Record.recordValue({}); // TypeError
Record.recordValue(); // TypeError
```
> Switch out `Record.isRecord` for `Record.recordValue`

- spec/abstract-operations.html
- spec/expression.html
- spec/immutable-data-structures.html
Fixes #339 
Moves the logic for handling duplicate keys into a new AO so can be re-used in the two places we need to handle duplicates.
Originally I inlined the logic directly into `createRecord` but decided a new AO only where its needed would put less work on engine authors to work out when they could skip the extra list processing.
> Record.fromEntries handles duplicate keys

- spec/ordinary-and-exotic-object-behaviours.html
PR based on suggestions from @anba and @ljharb in #343 
**Pro**: This approach reuses [validateandapplypropertydescriptor](https://tc39.es/ecma262/#sec-validateandapplypropertydescriptor) logic rather than reimplementing it.
**Con**: Less clear to implementers how to implement this in the least number of steps (if they wanted to optimize this operation)
> refactors record define own property

- spec/abstract-operations.html
- spec/data-types-and-values.html
- spec/expression.html
- spec/fundamental-objects.html
- spec/lexical-grammar.html
- spec/ordinary-and-exotic-object-behaviours.html
- spec/purely-editorial.html
(except for IsConcatSpreadable, which should be 23.1.3.2.1, but would need to be moved to its own imported file first)
> [spec]: fix step numbers

- spec/ordinary-and-exotic-object-behaviours.html
Fixes #352 
An empty property descriptor should return true.
cc: @catamorphism
> [spec] fix tuple-exotic-objects-defineownproperty

- spec/abstract-operations.html
- spec/data-types-and-values.html
- spec/immutable-data-structures.html
Implements a _useful_ `toString` for records and tuples.  Heavily based on @rickbutton 's [previous branch](https://github.com/tc39/proposal-record-tuple/commits/rb/useful-tostring).
```javascript
#[Symbol("s"), 99999n, #{ a: undefined, "\n": "s\"" } ].toString()
// `#[Symbol(s), 99999, #{ "a": undefined, "\n": "s\"" }]`
```
Fixes #136
> [spec] Records and Tuples have a useful toString

- NS-Proto-Appendix.md
- spec/immutable-data-structures.html
This PR provides `Record[@@hasInstance]` as an alternative function that can provide a brand check for Record Objects. Letting `Record.recordValue` be removed. The benefits of this are:
- A non-enumeralable symbol based API is less visible that  the string based `Record.recordValue` API. Resulting in fewer developers feeling the need to learn about it
- Because of `Record.prototype === null`, the default behavior it would inherit from `Function.prototype[@@hasInstance]` throws a `TypeError`.
```javascript
// before:
#{} instanceof Record;                 // false (primitives always return false for instanceof)
Object(#{}) instanceof Record;         // TypeError
Object.create(null) instanceof Record; // TypeError
// now:
#{} instanceof Record;                 // false (as above) …
```
> spec: use Record[@@hasInstance] for a brand check

- tutorial/en.md
Editorial: Changed /it's/ to /its/ in order to reflect possessive.
> fixed typo

- spec/abstract-operations.html
- spec/expression.html
- spec/immutable-data-structures.html
- spec/miscellaneous-updates.html
- spec/structured-data.html
I didn't add support for:
- `Reflect.*`, since they already disallow primitives even if it would make sense to use them (e.g. `Reflect.get("str", 0)`).
- Proxy handler (`new Proxy(target, #{})`), since it's meant to contain functions so a record would only work as an empty handler.
- ~~`JSON.stringify`'s replacer array, just to avoid conflicts with https://github.com/tc39/proposal-record-tuple/pull/257: I'll do it in a separate PR in the future~~ EDIT: done. ~~There are also a bunch of bugs in the current JSON implementation, where we pass R/T to AOs that expects objects.~~
Closes #107
This PR should be reviewed commit-by-commit. Most algorithms in the `misc-updates.html` file are copied from the existing spec (except for `InitializeTypedArrayFromTuple` and `UnwrapIteratorResult`): focus …
> Expand R&T support across methods that accept objects and arrays

- spec/immutable-data-structures.html
As discussed in today's plenary. Uses `IsArrayOrTuple` from #264.
> change Tuple#concat to spread on IsArrayOrTuple, not IsConcatSpreadable

- spec/ordinary-and-exotic-object-behaviours.html
The [[GetOwnProperty]] algorithm for Tuple exotic objects has an early exit step for symbol keys, but the step returned false, which isn’t a possible [[GetOwnProperty]] return value. It should return undefined.
(TEO’s [[DefineOwnProperty]] never permits definition of such a property, so it’s known not to exist. The explicit early exit is not redundant, though, because the subsequent CanonicalNumericIndexString(P) only has defined behavior for string input.)
> Correct Tuple exotic object [[GetOwnProperty]] return type

- spec/immutable-data-structures.html
Closes #323.
This has normative effect, because tuples are not casted anymore to objects when passing it to the various callbacks.
> Add explicit tuple methods steps
