tc39/proposal-record-tuple

README.md

* Corrects `ConstUpdateExpresion` to `ConstUpdateExpression`

Fixes typo in syntax definitions

---

README.md

include note about follow up proposals around update syntax

---

README.md

Update proposal motivations

---

Deep-Spread.md
README.md

small write up of a possible follow up proposal solving the "deep update" problem via deep spread syntax.

added small explainer for deep spread follow up proposal

---

README.md

Fix typo "asset" -> "assert"

---

NS-Proto-Appendix.md
README.md

Instead of push/pop/etc... be overridden, we keep them the same but create new methods in the past sense

New past tense methods

---

.github/issue_template.md

update issue template to reflect stage 1

update issue template to reflect stage 1

---

README.md

added playground link to the explainer

---

README.md

Added examples of destructuring

---

README.md

prevent symbols as keys

---

NS-Proto-Appendix.md

allow Record.fromEntries to consume iterable of array-likes

---

README.md

Switch to SameValueZero comparison semantics

---

spec.html
spec/abstract-operations.html
spec/data-types-and-values.html
spec/expression.html
spec/immutable-data-structures.html

Record and Tuple abstract ops

---

spec/abstract-operations.html
spec/data-types-and-values.html
spec/expression.html
spec/ordinary-and-exotic-object-behaviours.html

Based on #132. Will rebase on main branch after #132 gets merged.

Attach algorithms to grammar and fix previous bad merge

---

README.md

Fix definition of tuple in glossary

---

spec/immutable-data-structures.html

I'm not entirely sure the right way to word this bit of prose while keeping the amount of duplication low. Suggestions welcome.

simplification of Tuple.prototype.sorted

---

README.md

I also tweaked the wording for the "boxing objects" section, we haven't updated that section since iterating on the problem space via Symbols as WeakMap keys.

Broke off some things into a separate rationale section

---

README.md

Reopening here: https://github.com/progfay/proposal-record-tuple/pull/1

doc(Tuple): replace document var in example

---

README.md

I had a bit of a proofread and made a few clarifying fixes.

Update README with minor fixes

---

package-lock.json
package.json

Update lockfile to use public npm

---

README.md

This PR fixes some small typos, grammatical issues, and word choices in README.md.

Fix small typos and grammar in README.md

---

spec/immutable-data-structures.html

Fixes https://github.com/tc39/proposal-record-tuple/issues/237

Throw when using symbol keys in the `Record` constructor

---

spec/immutable-data-structures.html

We want this proposal to be aligned with the methods introduced in the Change Array by Copy proposal, so this PR is "porting" https://github.com/tc39/proposal-change-array-by-copy/pull/41

Update methods from the Change Array by Copy proposal

---

README.md
cookbook/en.md
tutorial/en.md

Update tuto & cookbook

---

cookbook/en.md

Some initial typos found while turning the examples into implementation tests.

Fixed two typos in cookbook/en.md

---

README.md

Update README.md to fix TS example typo

---

README.md

As the README has grown, maybe worth adding a TOC at the top?

add table of contents to top of README

---

spec/immutable-data-structures.html

adds Tuple.prototype.at

---

spec/immutable-data-structures.html

fix typo in Tuple.prototype.with

---

spec/immutable-data-structures.html

Add `Tuple.prototype.{ findLast, findLastIndex }`

---

spec/data-types-and-values.html
spec/overview.html

This PR solves the minor comments from #306. It doesn't solve yet the completion records updates.

Minor editorial updates

---

package.json
spec/data-types-and-values.html
spec/expression.html
spec/ordinary-and-exotic-object-behaviours.html

Fixes found during a spec review with @acutmore

various: Spec fixups

---

spec/ordinary-and-exotic-object-behaviours.html

fix record-exotic-objects-defineownproperty

---

spec/ordinary-and-exotic-object-behaviours.html

spec: fix isValidTupleIndex
